# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDomain',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, verbose_name='Domain Name')),
                ('name', models.CharField(blank=True, max_length=255,
                                          null=True, verbose_name='Optional Friendly Name')),
                ('description', models.TextField(blank=True,
                                                 null=True, verbose_name='Optional Description')),
            ],
            options={
                'verbose_name': 'Domain Name',
                'verbose_name_plural': 'Domain Names',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(
                    max_length=255, verbose_name='Version Name')),
            ],
            options={
                'verbose_name': 'Operating System',
                'verbose_name_plural': 'Operating Systems',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystemArch',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='OS Arch Name')),
            ],
            options={
                'verbose_name': 'Operating System Architecture',
                'verbose_name_plural': 'Operating System Architectures',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystemDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=255, verbose_name='OS Distribution')),
            ],
            options={
                'verbose_name': 'Operating System Distribution',
                'verbose_name_plural': 'Operating System Distributions',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystemPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='OS Type Name')),
            ],
            options={
                'verbose_name': 'Operating System Platform',
                'verbose_name_plural': 'Operating System Platforms',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255,
                                          null=True, verbose_name='Optional Friendly Name')),
                ('hostname', models.CharField(
                    max_length=255, verbose_name='Hostname')),
                ('ip', models.CharField(blank=True, help_text='Will be automatically populated if the domain is registered.',
                                        max_length=255, null=True, verbose_name='IP Address')),
                ('description', models.TextField(blank=True,
                                                 null=True, verbose_name='Optional Description')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='ServerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Server Category',
                'verbose_name_plural': 'Server Categories',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.ServerCategory', verbose_name='Server Category'),
        ),
        migrations.AddField(
            model_name='server',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.NetworkDomain', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='server',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.OperatingSystem', verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='operatingsystemdistribution',
            name='platform',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='hostmanager.OperatingSystemPlatform'),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.OperatingSystemArch', verbose_name='Architecture'),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.OperatingSystemDistribution', verbose_name='Distribution'),
        ),
    ]
