# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, help_text='Will be automatically        populated if the domain is registered.',
                                   max_length=255, null=True, verbose_name='IP Address'),
        ),
    ]
