# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0002_auto_20170929_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='hostmanager.ServerCategory', verbose_name='Server Category'),
        ),
    ]
